###  REGISTRAR USUARIO
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtYmFyIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJlbWFpbCI6ImFtYmFyQGdtYWlsLmNvbSJ9.g51YzGvZ4oxMWEN3Sn6wVprDKldt7GQ22NA3ZeYQJWM

{
    "username": "darlin",
    "password": "1234",
    "email": "darlin@gmail.com"
}

### INICIAR SESION OK
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdW1tYXNvZnQiLCJhcHAiOiJhdXRoIn0.puyHAVJ0gFi7qAixc_0iEFKkmib7k_wtrmnZYOCWNIQ

{
    "username": "ambar",
    "password": "1234"
}

### CERRAR SESIÓN
GET http://localhost:3000/api/auth/logout HTTP/1.1
Content-Type: application/json
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtYmFyIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJlbWFpbCI6ImFtYmFyQGdtYWlsLmNvbSJ9.g51YzGvZ4oxMWEN3Sn6wVprDKldt7GQ22NA3ZeYQJWM

### INICIAR SESION FAIL
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "unknowuser",
    "password": "123456"
}

### AUTENTICAR OK 
POST http://localhost:3000/api/auth/authenticate HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdW1tYXNvZnQiLCJhcHAiOiJhdXRoIn0.puyHAVJ0gFi7qAixc_0iEFKkmib7k_wtrmnZYOCWNIQ

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtYmFyIiwiaWF0IjoxNzQ0NjU1NjY5fQ.j2zhsfBgQCGwSH1FSg-4X95-AGXNJ3EszmkuxZziHK0"
}

### AUTENTICAR ERROR
POST http://localhost:3000/api/auth/authenticate HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdW1tYXNvZnQiLCJzdWIiOiJzb3BvcnRlIiwiYXBwIjoiYXBpIn0._8PaVQPzqIxm6XHGmgE7lIThpCYHpzq2Bw4dkfr-4yY

{
  "token": "OyJhbGeciiJI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhcmxpbiIsImlhdCI6MTczMDEzMDI1NH0.A7tZ0ylkk8j7q6jd-iD7vvsJbX2iGp2Ha8VhSbIwCqM"
}


### ESTO DEBE FALLAR, NO SON DEL TIPO DE DATOS ESPERADO
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdW1tYXNvZnQiLCJzdWIiOiJzb3BvcnRlIiwiYXBwIjoiYXBpIn0._8PaVQPzqIxm6XHGmgE7lIThpCYHpzq2Bw4dkfr-4yY


{
    "username": "",
    "password": {},
    "email": 1234
}

### ESTO DEBE FALLAR, HAY CAMPOS NO ESPERADOS
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdW1tYXNvZnQiLCJzdWIiOiJzb3BvcnRlIiwiYXBwIjoiYXBpIn0._8PaVQPzqIxm6XHGmgE7lIThpCYHpzq2Bw4dkfr-4yY

{
    "username": "cdiazlora",
    "password": "13456"
}

### VERIFICAR UN TOKEN 
POST http://localhost:3000/api/auth/verify HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdW1tYXNvZnQiLCJhcHAiOiJhdXRoIn0.puyHAVJ0gFi7qAixc_0iEFKkmib7k_wtrmnZYOCWNIQ

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNkaWF6bG9yYSIsImlhdCI6MTczMDQwMDA4Nn0.pN1GbpjgMcT8r-3vp-jLIBK1EbzHK6RKpQKCcPXUqkA"
}

### url del portal 
GET http://localhost:3000/api/auth/portal HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdW1tYXNvZnQiLCJhcHAiOiJhdXRoIn0.puyHAVJ0gFi7qAixc_0iEFKkmib7k_wtrmnZYOCWNIQ

### Listado
GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtYmFyIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJlbWFpbCI6ImFtYmFyQGdtYWlsLmNvbSJ9.g51YzGvZ4oxMWEN3Sn6wVprDKldt7GQ22NA3ZeYQJWM

### Actualizar
PATCH http://localhost:3000/api/users/ambar HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtYmFyIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJlbWFpbCI6ImFtYmFyQGdtYWlsLmNvbSJ9.g51YzGvZ4oxMWEN3Sn6wVprDKldt7GQ22NA3ZeYQJWM

{
  "password": "123489"
}